[tox]
envlist = pre-commit,pinned,py39,py310,py311,py312,py313

[testenv]
deps =
    pytest
commands =
    pytest {posargs:tests}

[testenv:pinned]
basepython = python3.9
deps =
    {[testenv]deps}
;     frontera==0.7.1
    scrapy==1.7.0
    # For scrapy==1.7.0:
    cryptography==35.0.0
    pyOpenSSL==21.0.0
    twisted==19.2.0

[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run --all
